Custom fields
AbhishekDoshi26/contactus pull request #17
Opened 2023-10-18 04:51 UTC by Riktam-Santra

## Description

Added a customSocials field which allows users to create their own fields with their parameters including icons, name and url

Resolves #16 

## Basic Checklist

- [x] ✨ Ran `dartdoc`
- [x] 🛠️ Added proper documentation
- [x] ❌ No warnings or errors in the code
- [x] ✅ If added a new parameter, added in Readme and example too

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2023-10-18 04:53 UTC, Riktam-Santra commented
In the example I have added my socials since I didn't have a good example, you might want to change that so I haven't updated the screenshot yet on README

2023-10-18 07:52 UTC, Riktam-Santra commented
Also, looks like your repository has been marked as excluded, you might want to enquire about that

2023-10-22 15:07 UTC, AbhishekDoshi26 requested changes
Also, inside models folder, there should be a barrlel file that will export cutom_field.dart
Same way, inside contactus.dart, add an export to models/models.dart

2023-10-22 15:07 UTC, AbhishekDoshi26 commented on README.md
> +                url: "https://discordapp.com/users/712546092612583424"),
Use fake names instead of real ones.

2023-10-22 15:07 UTC, AbhishekDoshi26 commented on example/lib/main.dart
> +                url: "https://discordapp.com/users/712546092612583424"),
Same here

2023-10-22 15:07 UTC, AbhishekDoshi26 commented on lib/models/custom_field.dart
> +      {required this.icon, required this.name, required this.url});
Add a trailing comma.

2023-10-22 18:19 UTC, Riktam-Santra commented on lib/models/custom_field.dart
> +      {required this.icon, required this.name, required this.url});
I committed the requested changes

2023-10-29 04:28 UTC, Riktam-Santra commented on lib/models/custom_field.dart
> +      {required this.icon, required this.name, required this.url});
@AbhishekDoshi26

2023-10-29 04:32 UTC, AbhishekDoshi26 approved these changes

2023-10-29 04:34 UTC, merged